// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kendall_tau_sign_cpp
List kendall_tau_sign_cpp(NumericVector X, NumericVector Y);
RcppExport SEXP _acor_kendall_tau_sign_cpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_tau_sign_cpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// kendall_tau_a
double kendall_tau_a(NumericVector X, NumericVector Y);
RcppExport SEXP _acor_kendall_tau_a(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_tau_a(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// kendall_tau_b
double kendall_tau_b(NumericVector X, NumericVector Y);
RcppExport SEXP _acor_kendall_tau_b(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_tau_b(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// goodman_kruskal_gamma
double goodman_kruskal_gamma(NumericVector X, NumericVector Y);
RcppExport SEXP _acor_goodman_kruskal_gamma(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(goodman_kruskal_gamma(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// kendall_tau_b_mod
double kendall_tau_b_mod(NumericVector X, NumericVector Y);
RcppExport SEXP _acor_kendall_tau_b_mod(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_tau_b_mod(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// H_bar_vec_v2_cpp
NumericVector H_bar_vec_v2_cpp(NumericVector X, NumericVector Y);
RcppExport SEXP _acor_H_bar_vec_v2_cpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(H_bar_vec_v2_cpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// kernel_agc_v2_cpp
NumericVector kernel_agc_v2_cpp(NumericVector x_rank, NumericVector y_rank, double rho);
RcppExport SEXP _acor_kernel_agc_v2_cpp(SEXP x_rankSEXP, SEXP y_rankSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_rank(x_rankSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_rank(y_rankSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_agc_v2_cpp(x_rank, y_rank, rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_acor_kendall_tau_sign_cpp", (DL_FUNC) &_acor_kendall_tau_sign_cpp, 2},
    {"_acor_kendall_tau_a", (DL_FUNC) &_acor_kendall_tau_a, 2},
    {"_acor_kendall_tau_b", (DL_FUNC) &_acor_kendall_tau_b, 2},
    {"_acor_goodman_kruskal_gamma", (DL_FUNC) &_acor_goodman_kruskal_gamma, 2},
    {"_acor_kendall_tau_b_mod", (DL_FUNC) &_acor_kendall_tau_b_mod, 2},
    {"_acor_H_bar_vec_v2_cpp", (DL_FUNC) &_acor_H_bar_vec_v2_cpp, 2},
    {"_acor_kernel_agc_v2_cpp", (DL_FUNC) &_acor_kernel_agc_v2_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_acor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
