# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kendall_tau_sign_cpp <- function(X, Y) {
    .Call(`_acor_kendall_tau_sign_cpp`, X, Y)
}

H_bar_vec_v2_cpp <- function(X, Y) {
    .Call(`_acor_H_bar_vec_v2_cpp`, X, Y)
}

kernel_agc_v2_cpp <- function(x_rank, y_rank, rho) {
    .Call(`_acor_kernel_agc_v2_cpp`, x_rank, y_rank, rho)
}

