# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kendall_tau_sign_cpp <- function(X, Y) {
    .Call(`_acor_kendall_tau_sign_cpp`, X, Y)
}

kendall_tau_a <- function(X, Y) {
    .Call(`_acor_kendall_tau_a`, X, Y)
}

kendall_tau_b <- function(X, Y) {
    .Call(`_acor_kendall_tau_b`, X, Y)
}

goodman_kruskal_gamma <- function(X, Y) {
    .Call(`_acor_goodman_kruskal_gamma`, X, Y)
}

H_bar_vec_v2_cpp <- function(X, Y) {
    .Call(`_acor_H_bar_vec_v2_cpp`, X, Y)
}

kernel_agc_v2_cpp <- function(x_rank, y_rank, rho) {
    .Call(`_acor_kernel_agc_v2_cpp`, x_rank, y_rank, rho)
}

agc_ij_cpp <- function(X, Y) {
    .Call(`_acor_agc_ij_cpp`, X, Y)
}

agc_ij_variance_cpp <- function(X, Y) {
    .Call(`_acor_agc_ij_variance_cpp`, X, Y)
}

akc_ij_cpp <- function(X, Y) {
    .Call(`_acor_akc_ij_cpp`, X, Y)
}

akc_ij_variance_cpp <- function(X, Y) {
    .Call(`_acor_akc_ij_variance_cpp`, X, Y)
}

rho_b_ij_cpp <- function(X, Y) {
    .Call(`_acor_rho_b_ij_cpp`, X, Y)
}

tau_b_ij_cpp <- function(X, Y) {
    .Call(`_acor_tau_b_ij_cpp`, X, Y)
}

gamma_ij_cpp <- function(X, Y) {
    .Call(`_acor_gamma_ij_cpp`, X, Y)
}

